name: canonical_url
description: The UrlCanonicalizer is used for the process of converting an URL into a canonical (normalized) form.
version: 1.1.0
homepage: https://github.com/isoos/canonical_url

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  path: ^1.5.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.0.0
