name: canonical_url
description: The UrlCanonicalizer is used for the process of converting an URL into a canonical (normalized) form.
version: 1.0.5
homepage: https://github.com/isoos/canonical_url

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  path: ^1.5.1

dev_dependencies:
  pedantic: 1.8.0
  test: ^1.0.0
